### ISSUE TITLE
FEATURE REQUEST: Support $JVM_OPTS or some other envvar

### ISSUE THREAD

**Issue by guns** [Raynes/lein-bin#13]
Hi,

I found it necessary to patch lein-bin to add java command options from the environment (gc options + some system properties). Could you please add $JVM_OPTS (or whatever you like) to the exec lines to make this possible?

Cheers,
guns

**Comment by Raynes** [comment]
It does have support for `:jvm-opts` in project.clj upon creation of the executable. You want to be able to set some JVM options after the executable has been created, so that it inherits them from an environment variable when it starts up?

I'd take a patch to add this.

**Comment by guns** [comment]
> so that it inherits them from an environment variable when it starts up?

Yes. For instance, I wear tinfoil hats and delete my system's CA truststore, so I have to set -Djavax.net.ssl.trustStore=… on launch, but I don't want that hard-coded in the executable.

> I'd take a patch to add this.

Is JVM_OPTS good for you?

**Comment by Raynes** [comment]
Tinfoil hats are trendy.

JVM_OPTS seems fine to me.
