### ISSUE TITLE
File not Found Exception

### ISSUE THREAD

**Issue by tbelahi** [Raynes/lein-bin#21]
When using lein-bin to create an executable error I get a java.io.FileNotFoundException. The output of lein-bin is exactly:

> Created /home/thomas/Documents/clojure/new-post/new-post-lein/target/uberjar/new-post-0.1.0-SNAPSHOT.jar
> Created /home/thomas/Documents/clojure/new-post/new-post-lein/target/uberjar/new-post-0.1.0-SNAPSHOT-standalone.jar
> Creating standalone executable: /home/thomas/Documents/clojure/new-post/new-post-lein/target/base+system+user+dev/new-jekyll-post
> java.io.FileNotFoundException: /home/thomas/Documents/clojure/new-post/new-post-lein/target/new-post-0.1.0-SNAPSHOT-standalone.jar (No such file or directory)

The problem is that lein-bin does not look in the right place and "/uberjar/" is missing in the path. This comes from line 58 of bin.clj. I guess `(fs/file jarfile)` is procuding `/home/thomas/Documents/clojure/new-post/new-post-lein/target/new-post-0.1.0-SNAPSHOT-standalone.jar` instead of `/home/thomas/Documents/clojure/new-post/new-post-lein/target/uberjar/new-post-0.1.0-SNAPSHOT-standalone.jar`

**Comment by timothyrenner** [comment]
I'm seeing a similar issue. Were you able to find a workaround?

**Comment by nsjph** [comment]
I've had the same issue recently using Lein 2.5.1 on OpenJDK 7 and latest lein-bin.

**Comment by Gastove** [comment]
Same issue. No workarounds emerging, eh?

**Comment by Raynes** [comment]
I'm guessing leiningen recently started putting uberjars in a new directory? The work around is probably a 5 minute pull request to fix it. There's not much code here, and this is almost certainly a one line fix.

**Comment by Raynes** [comment]
https://github.com/Raynes/lein-bin/blob/master/src/leiningen/bin.clj#L51

In addition, it looks like I'm relying on leiningen giving me the path to the uberjar it creates. If it's giving the wrong path, not much we can do about it other than make the path ourself.

**Comment by Gastove** [comment]
Yeah, was just poking this. It looks like lein is now compiling profiles to paths like `target/profiles+concatenated+with+plusses/actual-jar`. So that's... neat.

**Comment by Gastove** [comment]
Cool story: if I just `lein install` `lein-bin` on my local workstation with a new version number and use that, it immediately works flawlessly. Maybe some kind of weirdness with the released jar?

**Comment by Raynes** [comment]
Interesting. Guess it's time for a new release

**Comment by Raynes** [comment]
Just released 0.3.5. Please lemme know if this resolves the issue!

**Comment by Gastove** [comment]
Works like a freaking champ. Hooray, mysterious weirdness with compiled code?

Thanks for doing that so promptly! Much appreciated.

**Comment by Raynes** [comment]
Thanks for poking around and doing all the work for me.
