### ISSUE TITLE
Magical expression does not work in eshell

### ISSUE THREAD

**Issue by dakrone** [Raynes/lein-bin#22]
This is probably the lamest bug report ever, but the "magic" that `lein-bin` adds to scripts does not work in [eshell](https://www.gnu.org/software/emacs/manual/html_mono/eshell.html):

```
λ| stream2es
/Applications/Emacs.app/Contents/MacOS/Emacs: /Users/hinmanm/bin/stream2es: Exec format error
```

I believe eshell can't tell that this should be interpreted as a shell script, using `bash /path/to/thing` fixes the problem.

Not sure if lein-bin can fix this, but I thought I would at least report it.

**Comment by Raynes** [comment]
Haha, no bug report is lame sir. Thank you.

I'm unsurprised this doesn't work. Honestly, I don't really have a solid understanding of how this works. The library was a direct port of a cake plugin @ninjudd wrote. I doubt that it can be fixed to work in eshell. It's a giant hack regardless.

Perhaps Justin might know.

**Comment by Raynes** [comment]
Yeah, I'm gonna assume this is unfixable.

**Comment by dakrone** [comment]
Works for me :)
